### ISSUE TITLE
404 on etc page

### ISSUE THREAD

**Issue by tobegit3hub** [yeasy/openstack_code_Neutron#1]
Please checkout http://yeasy.gitbooks.io/content/book/yeasy/openstack_code_neutron/etc/index.html

It's the next page of http://yeasy.gitbooks.io/openstack_code_neutron/content/etc/initd.html

**Comment by yeasy** [comment]
Fixed, thanks!

**Comment by tobegit3hub** [comment]
Nice :+1:
